using System.Web.Mvc;
using System.Web.Routing;

namespace NecroNet.Toolkit.Web.Mvc
{
	public static class RouteCollectionExtensions
	{
		/// <summary>
		/// Adds a route to the end of the route collection. Route acts as 'lowercase' route - that means all urls generated by MVC framework base on this route will be in lowercase.
		/// </summary>
		/// <param name="routes">The route collection to add route to.</param>
		/// <param name="name">The name of the route.</param>
		/// <param name="url">The URL pattern for the route.</param>
		/// <param name="defaults">The values to use if URL doesn't contain all parameters.</param>
		/// <param name="constraints">A regular expression that the specified valid values for a URL parameter.</param>
		/// <param name="namespaces">Namespace that uniquely identifies the controller to use.</param>
		public static LowercaseRoute MapLowercaseRoute(this RouteCollection routes, string name, string url, object defaults = null, object constraints = null, string[] namespaces = null)
		{
			if(routes == null)
			{
				Throw.NewArgumentNullException(() => routes);
			}

			if(url == null)
			{
				Throw.NewArgumentNullException(() => url);
			}

			var route = new LowercaseRoute(url, new MvcRouteHandler())
			            	{
			            		Defaults = new RouteValueDictionary(defaults),
			            		Constraints = new RouteValueDictionary(constraints),
			            		DataTokens = new RouteValueDictionary()
			            	};

			if(namespaces != null && namespaces.Length > 0)
			{
				route.DataTokens["Namespaces"] = namespaces;
			}

			routes.Add(name, route);

			return route;
		}
	}
}