//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NecroNetToolkit.Web.Model
{
    public partial class City
    {
        public City()
        {
            this.ActualDeals = new HashSet<ActualDeal>();
            this.HistoryDeals = new HashSet<HistoryDeal>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> State { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<ActualDeal> ActualDeals { get; set; }
        public virtual State State1 { get; set; }
        public virtual ICollection<HistoryDeal> HistoryDeals { get; set; }
    }
    
}
