//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NecroNetToolkit.Web.Model
{
    public partial class HistoryDeal
    {
        public int ID { get; set; }
        public string DealName { get; set; }
        public string DealID { get; set; }
        public int CityID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Image { get; set; }
        public int Final_Price { get; set; }
        public int Original_Price { get; set; }
        public Nullable<int> Customers { get; set; }
        public Nullable<int> MinCustomers { get; set; }
        public Nullable<int> MaxCustomers { get; set; }
        public Nullable<System.DateTime> DealStart { get; set; }
        public Nullable<System.DateTime> DealEnd { get; set; }
        public Nullable<System.DateTime> VoucherStart { get; set; }
        public Nullable<System.DateTime> VoucherEnd { get; set; }
        public string Address { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<decimal> MDetail { get; set; }
        public Nullable<decimal> FDetail { get; set; }
        public Nullable<decimal> MClick { get; set; }
        public Nullable<decimal> FClick { get; set; }
        public Nullable<decimal> MDeal { get; set; }
        public Nullable<decimal> FDeal { get; set; }
        public Nullable<decimal> Recommend { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string ImageSmall { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public Nullable<decimal> MRank { get; set; }
        public Nullable<decimal> FRank { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> MaleRank { get; set; }
        public Nullable<int> FemaleRank { get; set; }
        public Nullable<decimal> CharityDeal { get; set; }
        public Nullable<decimal> CharityClick { get; set; }
        public Nullable<System.DateTime> DealAdded { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Server Server { get; set; }
    }
    
}
