//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace NecroNetToolkit.Web.Model
{
    public partial class AllDealsEntities : DbContext
    {
        public AllDealsEntities()
            : base("name=AllDealsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActualDeal> ActualDeals { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<HistoryDeal> HistoryDeals { get; set; }
        public DbSet<Index> Indexes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<MetaCategory> MetaCategories { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
