//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NecroNetToolkit.Web.Model
{
    public partial class State
    {
        public State()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
    
}
