//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecroNet.Toolkit.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecroNet.Toolkit.Mvc.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider type was not set. Set it with SetDataProviderType during SelectListManager initialization..
        /// </summary>
        public static string ExceptionMessage_DataProviderTypeNotSet {
            get {
                return ResourceManager.GetString("ExceptionMessage_DataProviderTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select list with key &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string ExceptionMessage_SelectListManager_AlreadyRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_SelectListManager_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectListManager was not initialized. Call SelectListManager.Initialize() during application startup..
        /// </summary>
        public static string ExceptionMessage_SelectListManager_NotInitialized {
            get {
                return ResourceManager.GetString("ExceptionMessage_SelectListManager_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select list with key &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string ExceptionMessage_SelectListManager_NotRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_SelectListManager_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache provider type must implement ISelectListManagerCacheProvider..
        /// </summary>
        public static string ExceptionMessage_WrongCacheProviderType {
            get {
                return ResourceManager.GetString("ExceptionMessage_WrongCacheProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider type must implement ISelectListManagerDataProvider..
        /// </summary>
        public static string ExceptionMessage_WrongDataProviderType {
            get {
                return ResourceManager.GetString("ExceptionMessage_WrongDataProviderType", resourceCulture);
            }
        }
    }
}
