//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecroNet.Toolkit.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecroNet.Toolkit.Core.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type does not implement IDbContextFactory.
        /// </summary>
        public static string DbContextBuilder_TypeIsNotIDbContextFactory {
            get {
                return ResourceManager.GetString("DbContextBuilder_TypeIsNotIDbContextFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type does not implement IEntityToContextMap.
        /// </summary>
        public static string EntityToContextNavigator_TypeIsNotIEntityToContextMap {
            get {
                return ResourceManager.GetString("EntityToContextNavigator_TypeIsNotIEntityToContextMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section &apos;necroNetToolkit&apos; was not found..
        /// </summary>
        public static string ExceptionMessage_ConfigurationManager_SectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionMessage_ConfigurationManager_SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity set name..
        /// </summary>
        public static string ExceptionMessage_Repository_InvalidEntitySetName {
            get {
                return ResourceManager.GetString("ExceptionMessage_Repository_InvalidEntitySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EntitySetName attribute setup..
        /// </summary>
        public static string ExceptionMessage_Repository_InvalidEntitySetNameAttributeSetup {
            get {
                return ResourceManager.GetString("ExceptionMessage_Repository_InvalidEntitySetNameAttributeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select list with key &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string ExceptionMessage_SelectListManager_AlreadyRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_SelectListManager_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select list with key &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string ExceptionMessage_SelectListManager_NotRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_SelectListManager_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number can&apos;t be less than 1..
        /// </summary>
        public static string ExceptionMessage_SortedPagedList_PageNumber {
            get {
                return ResourceManager.GetString("ExceptionMessage_SortedPagedList_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size can&apos;t be less than 1..
        /// </summary>
        public static string ExceptionMessage_SortedPagedList_PageSize {
            get {
                return ResourceManager.GetString("ExceptionMessage_SortedPagedList_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction must be either SortDir.Asc or SortDir.Desc..
        /// </summary>
        public static string ExceptionMessage_SortedPagedList_SortDirection {
            get {
                return ResourceManager.GetString("ExceptionMessage_SortedPagedList_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort key cannot be null or empty..
        /// </summary>
        public static string ExceptionMessage_SortedPagedList_SortKey {
            get {
                return ResourceManager.GetString("ExceptionMessage_SortedPagedList_SortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfWork for type &apos;{0}&apos; was already registered..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_AlreadyRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default UnitOfWork factory was not registered. Make sure you called UnitOfWork.RegisterDefault() method before using default UnitOfWork..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_DefaultNotRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_DefaultNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This unit of work and it&apos;s object context has already been disposed..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_Disposed {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in a unit of work of type &apos;{0}&apos;..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_NotInUnitOfWork {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_NotInUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfWork factory for type &apos;{0}&apos; was not registered. Make sure you called UnitOfWork.Register() method before using UnitOfWork..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_NotRegistered {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot register more then one default unit of work..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_RegisterMoreThanOneDefault {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_RegisterMoreThanOneDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot start more than one unit of work of the same type at the same time..
        /// </summary>
        public static string ExceptionMessage_UnitOfWork_StartSecondAtTheSameTime {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnitOfWork_StartSecondAtTheSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find DbContext type for this entity type..
        /// </summary>
        public static string UnitOfWork_NoDbContextForEntity {
            get {
                return ResourceManager.GetString("UnitOfWork_NoDbContextForEntity", resourceCulture);
            }
        }
    }
}
